# Generated by Django 4.1.1 on 2022-09-26 17:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoApp', '0002_todo_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='due',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 26, 20, 28, 57, 644418)),
        ),
    ]
