# Generated by Django 4.1.1 on 2022-09-26 18:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoApp', '0003_todo_due'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='due',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 26, 21, 6, 0, 178955)),
        ),
    ]
